# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TiMiUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TiMiUi(object):
    def setupUi(self, TiMiUi):
        TiMiUi.setObjectName("TiMiUi")
        TiMiUi.resize(1046, 661)
        self.centralwidget = QtWidgets.QWidget(TiMiUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1051, 661))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Govind/Pictures/Saved Pictures/Wallpaper/AIbg.png"))
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 651, 491))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Govind/Pictures/Saved Pictures/Wallpaper/AIwave1.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 250, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 560, 151, 51))
        font = QtGui.QFont()
        font.setFamily("HP Simplified Jpan")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setToolTipDuration(-1)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(0, 243, 0);\n"
"color: rgb(0, 89, 89);\n"
"border-radius:15px;")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 560, 161, 51))
        font = QtGui.QFont()
        font.setFamily("HP Simplified Jpan")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: red;\n"
"color: rgb(0, 89, 89);\n"
"border-radius:15px;")
        self.pushButton_2.setObjectName("pushButton_2")
        TiMiUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(TiMiUi)
        QtCore.QMetaObject.connectSlotsByName(TiMiUi)

    def retranslateUi(self, TiMiUi):
        _translate = QtCore.QCoreApplication.translate
        TiMiUi.setWindowTitle(_translate("TiMiUi", "MainWindow"))
        self.label_3.setText(_translate("TiMiUi", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#00d1d1;\">TiMi</span></p></body></html>"))
        self.pushButton.setText(_translate("TiMiUi", "Invoke"))
        self.pushButton_2.setText(_translate("TiMiUi", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TiMiUi = QtWidgets.QMainWindow()
    ui = Ui_TiMiUi()
    ui.setupUi(TiMiUi)
    TiMiUi.show()
    sys.exit(app.exec_())
